spring.application.name=NovaCart

# spring.datasource.url=jdbc:mysql://localhost:3306/novaCart
spring.datasource.url=jdbc:mysql://localhost:3306/novacart_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Razorpay API Credentials
razorpay.api.key=rzp_test_TWndbSYXQrY289
razorpay.api.secret=94ax5ir1RhttNBiLBpzjdTzb